//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::file::Entity as File;
pub use super::subject::Entity as Subject;
pub use super::unit::Entity as Unit;
pub use super::user::Entity as User;
